version: '2'
services:
    first-node: &first-node
        container_name: first-node
        image: lopalo/dc
        ports:
            - "10611:10611"
            - "10621:10621"
            - "10622:10622"
        volumes:
            - "..:/dc"
        working_dir: /dc/server/bin
        tty: true
        command: ./server ../settings/dev_cluster.yaml first
    second-node:
        <<: *first-node
        container_name: second-node
        ports:
            - "10612:10612"
        command: ./server ../settings/dev_cluster.yaml second
    third-node:
        <<: *first-node
        container_name: third-node
        ports: []
        command: ./server ../settings/dev_cluster.yaml third
    fourth-node:
        <<: *first-node
        container_name: fourth-node
        ports: []
        command: ./server ../settings/dev_cluster.yaml fourth
    fifth-node:
        <<: *first-node
        container_name: fifth-node
        ports: []
        command: ./server ../settings/dev_cluster.yaml fifth
