
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "bootstrap"
  config.vm.synced_folder "../", "/dc"

  config.vm.network "forwarded_port", guest: 10501, host: 10501

  config.vm.provider "virtualbox" do |v|
    v.memory = 1500
    v.cpus = 2
  end
end
