areas: [alpha, beta]
start-area: alpha
node-address: [127.0.0.1, "10500"]
http-port: 10502
client-dir: ../../client
client-settings: ../../client_settings/dev.json
ws-address: &ws-address-1 [<host>, 10501]
ws-addresses: [*ws-address-1]
db: ../dbs/dev.db
user:
  speed: 60 #units per second
  init-durability: 100
  logout-seconds: 10
  period-milliseconds: 1000
area:
  enter-pos: [100, 100]
  shot-damage: 10
  route-filter-threshold: 10 #units
  tick-milliseconds: 50
  broadcast-every-tick: 4
  log-every-tick: 100
  sync-every-tick: 100
