ws-addresses: &ws-addresses
    - [dc-dev-host-example.net, &ws-port-1 10501]

cluster:
    respawn-delay-milliseconds: [500, 1200]
    node-ping-period-milliseconds: 1000

log:
    log-level: Debug
    stdout: true
    logFile: null
    aggregator-name: null

db:
    db-dir: ../dbs/dev

user:
    start-area: alpha
    size: [80, 40]
    speed: 300 # 60 # units per second
    init-durability: 100
    logout-seconds: 10
    period-milliseconds: 1000
    min-db-replicas: 1

area:
    gate-field-radius: 700
    shot:
        damage: 10
        distance: 1200
        cooldown-milliseconds: 100
    asteroid-pull-speed: 60 # units per second
    route-filter-threshold: 10 # units

    broadcast-cell-size: 1000 # units
    collision-cell-size: 300 # units

    tick-milliseconds: 50
    broadcast-every-tick: 1 # 4
    log-every-tick: 1000
    sync-every-tick: 100

http:
    client-dir: ../../client
    client-settings: ../../client_settings/dev.json
    ws-addresses:
        - [<http-host>, *ws-port-1]

admin:
    ui-dir: ../../admin

nodes:
    first:
        node-host: localhost
        node-port: 10500
        services:
            - type: user-db
              ident: "[0-2]|a"

            - type: user-db
              ident: "[1-2]|a"

            - type: ws
              ident: one
              host: 0.0.0.0
              port: *ws-port-1

            - type: http
              ident: one
              host: 0.0.0.0
              port: 10502

            - type: admin
              ident: one
              host: 0.0.0.0
              port: 10503


            - type: area-db
              ident: "alpha|a"

            - type: area-db
              ident: "beta|a"

            - type: area-db
              ident: "gamma|a"

            - type: area
              ident: alpha
              min-db-replicas: 1

            - type: area
              ident: beta
              min-db-replicas: 1

            - type: area
              ident: gamma
              min-db-replicas: 1




