#!/bin/bash
DIR=`dirname $(readlink -f "$0")`/..
docker run \
    --name node \
    --rm \
    -p 10501:10501 \
    -p 10502:10502 \
    -p 10503:10503 \
    -v $DIR:/dc \
    -t -i lopalo/dc \
    run_dev_server
