#!/usr/bin/python

import sys
import os
import plyvel


def main():
    db_dir = sys.argv[1]
    for db_name in sys.argv[2:]:
        path = os.path.join(db_dir, db_name)
        plyvel.DB(path, create_if_missing=True).close()


if __name__ == "__main__":
    main()
