#!/usr/bin/python

import sys
import sqlite3


CREATE_USER = """
    CREATE TABLE user (
        id TEXT,
        name TEXT,
        area TEXT,
        speed INTEGER,
        max_durability INTEGER,
        durability INTEGER,
        width INTEGER,
        height INTEGER,
        kills INTEGER,
        deaths INTEGER,
        PRIMARY KEY (id)
    );
"""


CREATE_GATE = """
    CREATE TABLE gate (
        area TEXT,
        id TEXT,
        name TEXT,
        x INTEGER,
        y INTEGER,
        angle REAL,
        actions TEXT,
        width INTEGER,
        height INTEGER,

        PRIMARY KEY (id, area)
    );
"""


CREATE_ASTEROID = """
    CREATE TABLE asteroid (
        area TEXT,
        id TEXT,
        name TEXT,
        x INTEGER,
        y INTEGER,
        angle REAL,
        max_durability INTEGER,
        durability INTEGER,
        actions TEXT,
        width INTEGER,
        height INTEGER,

        PRIMARY KEY (id, area)
    );
"""


CREATE_CONTROL_POINT = """
    CREATE TABLE control_point (
        area TEXT,
        id TEXT,
        name TEXT,
        x INTEGER,
        y INTEGER,
        angle REAL,
        max_durability INTEGER,
        durability INTEGER,
        actions TEXT,
        width INTEGER,
        height INTEGER,
        owner TEXT,

        PRIMARY KEY (id, area)
    );
"""





def main():
    db_name = sys.argv[1]
    conn = sqlite3.connect(db_name)
    cur = conn.cursor()
    cur.executescript(CREATE_USER)
    cur.executescript(CREATE_GATE)
    cur.executescript(CREATE_ASTEROID)
    cur.executescript(CREATE_CONTROL_POINT)



if __name__ == "__main__":
    main()
