#!/usr/bin/python

import sys
from generate_area_objects import Settings, generate


def main():
    db_dir = sys.argv[1]
    area_db_names = sys.argv[2:]
    settings = Settings(
        asteroid_count=50,
        asteroid_size=(70, 200),
        asteroid_durability=(1000, 30000),
        asteroid_rotation_speed=(-15, 15),
        asteroid_field_radius=(300, 3500),
        asteroid_field_position=(100, 230),
        asteroid_trajectory_probability=0.5,

        gate_position=(100, 230),
        gate_rotation_speed=-20,
        gate_size=300,

        cp_position=(-2000, -100),
        cp_size=400,
        cp_durability=430
    )

    generate(db_dir, area_db_names, settings)


if __name__ == "__main__":
    main()


